"""add financial movements

Revision ID: 10c24a8a6f3a
Revises: 8f977026e374
Create Date: 2026-03-15 18:55:41.045716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c24a8a6f3a'
down_revision: Union[str, Sequence[str], None] = '8f977026e374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('source_financial_entry_id', sa.UUID(), nullable=True),
    sa.Column('source_purchase_entry_id', sa.UUID(), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('third_party_name', sa.String(length=255), nullable=True),
    sa.Column('third_party_tax_id', sa.String(length=100), nullable=True),
    sa.Column('concept', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('business_area', sa.String(length=100), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('withholding_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_financial_entry_id'], ['financial_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_purchase_entry_id'], ['purchase_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_movements_business_area'), 'financial_movements', ['business_area'], unique=False)
    op.create_index(op.f('ix_financial_movements_category'), 'financial_movements', ['category'], unique=False)
    op.create_index(op.f('ix_financial_movements_created_at'), 'financial_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_financial_movements_document_type'), 'financial_movements', ['document_type'], unique=False)
    op.create_index(op.f('ix_financial_movements_kind'), 'financial_movements', ['kind'], unique=False)
    op.create_index(op.f('ix_financial_movements_movement_date'), 'financial_movements', ['movement_date'], unique=False)
    op.create_index(op.f('ix_financial_movements_needs_review'), 'financial_movements', ['needs_review'], unique=False)
    op.create_index(op.f('ix_financial_movements_source_document_id'), 'financial_movements', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_financial_movements_source_financial_entry_id'), 'financial_movements', ['source_financial_entry_id'], unique=False)
    op.create_index(op.f('ix_financial_movements_source_purchase_entry_id'), 'financial_movements', ['source_purchase_entry_id'], unique=False)
    op.create_index(op.f('ix_financial_movements_source_type'), 'financial_movements', ['source_type'], unique=False)
    op.create_index(op.f('ix_financial_movements_status'), 'financial_movements', ['status'], unique=False)
    op.create_index(op.f('ix_financial_movements_subcategory'), 'financial_movements', ['subcategory'], unique=False)
    op.create_index(op.f('ix_financial_movements_tenant_id'), 'financial_movements', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_financial_movements_third_party_name'), 'financial_movements', ['third_party_name'], unique=False)
    op.create_index(op.f('ix_financial_movements_third_party_tax_id'), 'financial_movements', ['third_party_tax_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_movements_third_party_tax_id'), table_name='financial_movements')
    op.drop_index(op.f('ix_financial_movements_third_party_name'), table_name='financial_movements')
    op.drop_index(op.f('ix_financial_movements_tenant_id'), table_name='financial_movements')
    op.drop_index(op.f('ix_financial_movements_subcategory'), table_name='financial_movements')
    op.drop_index(op.f('ix_financial_movements_status'), table_name='financial_movements')
    op.drop_index(op.f('ix_financial_movements_source_type'), table_name='financial_movements')
    op.drop_index(op.f('ix_financial_movements_source_purchase_entry_id'), table_name='financial_movements')
    op.drop_index(op.f('ix_financial_movements_source_financial_entry_id'), table_name='financial_movements')
    op.drop_index(op.f('ix_financial_movements_source_document_id'), table_name='financial_movements')
    op.drop_index(op.f('ix_financial_movements_needs_review'), table_name='financial_movements')
    op.drop_index(op.f('ix_financial_movements_movement_date'), table_name='financial_movements')
    op.drop_index(op.f('ix_financial_movements_kind'), table_name='financial_movements')
    op.drop_index(op.f('ix_financial_movements_document_type'), table_name='financial_movements')
    op.drop_index(op.f('ix_financial_movements_created_at'), table_name='financial_movements')
    op.drop_index(op.f('ix_financial_movements_category'), table_name='financial_movements')
    op.drop_index(op.f('ix_financial_movements_business_area'), table_name='financial_movements')
    op.drop_table('financial_movements')
    # ### end Alembic commands ###
