"""add purchases and analytics models

Revision ID: 8f977026e374
Revises: 811971732335
Create Date: 2026-03-15 17:14:39.344177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f977026e374'
down_revision: Union[str, Sequence[str], None] = '811971732335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_metric_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('month_key', sa.String(length=7), nullable=False),
    sa.Column('metric_type', sa.String(length=30), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('units', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'month_key', 'metric_type', 'category_name', name='uq_category_metric_snapshots_tenant_month_type_category')
    )
    op.create_index(op.f('ix_category_metric_snapshots_category_name'), 'category_metric_snapshots', ['category_name'], unique=False)
    op.create_index(op.f('ix_category_metric_snapshots_created_at'), 'category_metric_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_category_metric_snapshots_metric_type'), 'category_metric_snapshots', ['metric_type'], unique=False)
    op.create_index(op.f('ix_category_metric_snapshots_month_key'), 'category_metric_snapshots', ['month_key'], unique=False)
    op.create_index(op.f('ix_category_metric_snapshots_tenant_id'), 'category_metric_snapshots', ['tenant_id'], unique=False)
    op.create_table('monthly_kpi_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('month_key', sa.String(length=7), nullable=False),
    sa.Column('total_sales_net', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_sales_gross', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_purchases_net', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_purchases_gross', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_margin_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_margin_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('purchase_to_sales_ratio_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('tickets_count', sa.Integer(), nullable=False),
    sa.Column('average_ticket', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('documents_processed', sa.Integer(), nullable=False),
    sa.Column('pending_reviews', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'month_key', name='uq_monthly_kpi_snapshots_tenant_month')
    )
    op.create_index(op.f('ix_monthly_kpi_snapshots_created_at'), 'monthly_kpi_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_monthly_kpi_snapshots_month_key'), 'monthly_kpi_snapshots', ['month_key'], unique=False)
    op.create_index(op.f('ix_monthly_kpi_snapshots_tenant_id'), 'monthly_kpi_snapshots', ['tenant_id'], unique=False)
    op.create_table('provider_metric_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('month_key', sa.String(length=7), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('documents_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'month_key', 'provider_name', name='uq_provider_metric_snapshots_tenant_month_provider')
    )
    op.create_index(op.f('ix_provider_metric_snapshots_created_at'), 'provider_metric_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_provider_metric_snapshots_month_key'), 'provider_metric_snapshots', ['month_key'], unique=False)
    op.create_index(op.f('ix_provider_metric_snapshots_provider_name'), 'provider_metric_snapshots', ['provider_name'], unique=False)
    op.create_index(op.f('ix_provider_metric_snapshots_tenant_id'), 'provider_metric_snapshots', ['tenant_id'], unique=False)
    op.create_table('purchase_import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('filename_original', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('rows_detected', sa.Integer(), nullable=False),
    sa.Column('rows_imported', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_import_batches_checksum'), 'purchase_import_batches', ['checksum'], unique=False)
    op.create_index(op.f('ix_purchase_import_batches_created_at'), 'purchase_import_batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_purchase_import_batches_source_document_id'), 'purchase_import_batches', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_purchase_import_batches_status'), 'purchase_import_batches', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_import_batches_tenant_id'), 'purchase_import_batches', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_purchase_import_batches_uploaded_by_user_id'), 'purchase_import_batches', ['uploaded_by_user_id'], unique=False)
    op.create_table('purchase_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('month_key', sa.String(length=7), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('row_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['purchase_import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'row_fingerprint', name='uq_purchase_entries_tenant_row_fingerprint')
    )
    op.create_index(op.f('ix_purchase_entries_category'), 'purchase_entries', ['category'], unique=False)
    op.create_index(op.f('ix_purchase_entries_created_at'), 'purchase_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_purchase_entries_import_batch_id'), 'purchase_entries', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_purchase_entries_issue_date'), 'purchase_entries', ['issue_date'], unique=False)
    op.create_index(op.f('ix_purchase_entries_month_key'), 'purchase_entries', ['month_key'], unique=False)
    op.create_index(op.f('ix_purchase_entries_order_date'), 'purchase_entries', ['order_date'], unique=False)
    op.create_index(op.f('ix_purchase_entries_provider_name'), 'purchase_entries', ['provider_name'], unique=False)
    op.create_index(op.f('ix_purchase_entries_row_fingerprint'), 'purchase_entries', ['row_fingerprint'], unique=False)
    op.create_index(op.f('ix_purchase_entries_source_document_id'), 'purchase_entries', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_purchase_entries_source_type'), 'purchase_entries', ['source_type'], unique=False)
    op.create_index(op.f('ix_purchase_entries_status'), 'purchase_entries', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_entries_subcategory'), 'purchase_entries', ['subcategory'], unique=False)
    op.create_index(op.f('ix_purchase_entries_tenant_id'), 'purchase_entries', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_memberships_tenant_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_memberships_tenant_id'), 'memberships', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_purchase_entries_tenant_id'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_subcategory'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_status'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_source_type'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_source_document_id'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_row_fingerprint'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_provider_name'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_order_date'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_month_key'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_issue_date'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_import_batch_id'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_created_at'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_category'), table_name='purchase_entries')
    op.drop_table('purchase_entries')
    op.drop_index(op.f('ix_purchase_import_batches_uploaded_by_user_id'), table_name='purchase_import_batches')
    op.drop_index(op.f('ix_purchase_import_batches_tenant_id'), table_name='purchase_import_batches')
    op.drop_index(op.f('ix_purchase_import_batches_status'), table_name='purchase_import_batches')
    op.drop_index(op.f('ix_purchase_import_batches_source_document_id'), table_name='purchase_import_batches')
    op.drop_index(op.f('ix_purchase_import_batches_created_at'), table_name='purchase_import_batches')
    op.drop_index(op.f('ix_purchase_import_batches_checksum'), table_name='purchase_import_batches')
    op.drop_table('purchase_import_batches')
    op.drop_index(op.f('ix_provider_metric_snapshots_tenant_id'), table_name='provider_metric_snapshots')
    op.drop_index(op.f('ix_provider_metric_snapshots_provider_name'), table_name='provider_metric_snapshots')
    op.drop_index(op.f('ix_provider_metric_snapshots_month_key'), table_name='provider_metric_snapshots')
    op.drop_index(op.f('ix_provider_metric_snapshots_created_at'), table_name='provider_metric_snapshots')
    op.drop_table('provider_metric_snapshots')
    op.drop_index(op.f('ix_monthly_kpi_snapshots_tenant_id'), table_name='monthly_kpi_snapshots')
    op.drop_index(op.f('ix_monthly_kpi_snapshots_month_key'), table_name='monthly_kpi_snapshots')
    op.drop_index(op.f('ix_monthly_kpi_snapshots_created_at'), table_name='monthly_kpi_snapshots')
    op.drop_table('monthly_kpi_snapshots')
    op.drop_index(op.f('ix_category_metric_snapshots_tenant_id'), table_name='category_metric_snapshots')
    op.drop_index(op.f('ix_category_metric_snapshots_month_key'), table_name='category_metric_snapshots')
    op.drop_index(op.f('ix_category_metric_snapshots_metric_type'), table_name='category_metric_snapshots')
    op.drop_index(op.f('ix_category_metric_snapshots_created_at'), table_name='category_metric_snapshots')
    op.drop_index(op.f('ix_category_metric_snapshots_category_name'), table_name='category_metric_snapshots')
    op.drop_table('category_metric_snapshots')
    # ### end Alembic commands ###
