"""add_fingerprint_and_source_data

Revision ID: b468aee317a5
Revises: 4ebdccc7a191
Create Date: 2026-03-16 22:32:37.900427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b468aee317a5'
down_revision: Union[str, Sequence[str], None] = '4ebdccc7a191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_movements', sa.Column('fingerprint', sa.String(length=255), nullable=True))
    op.add_column('financial_movements', sa.Column('source_data', sa.Text(), nullable=True))
    op.create_index(op.f('ix_financial_movements_fingerprint'), 'financial_movements', ['fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_movements_fingerprint'), table_name='financial_movements')
    op.drop_column('financial_movements', 'source_data')
    op.drop_column('financial_movements', 'fingerprint')
    # ### end Alembic commands ###
